#!/bin/sh

if git diff --cached --name-only --diff-filter=ACMR -- '*.dart' | grep -q .; then
    echo "检测到 Dart 文件变动，执行 dart format..."

    git diff --cached --name-only --diff-filter=ACMR -z -- '*.dart' | xargs -0 dart format
    if [ $? -ne 0 ]; then
        echo "dart format 执行失败，提交已取消。"
        exit 1
    fi

    git diff --cached --name-only --diff-filter=ACMR -z -- '*.dart' | xargs -0 git add
    echo "已格式化 Dart 文件并加入本次提交。"
fi

# 检查 assets 目录下是否有变动
if git diff --cached --name-only | grep -q ^assets/; then
    echo "检测到 assets 目录变动，执行 generate_sites_manifest.sh..."

    # 执行脚本
    ./generate_sites_manifest.sh
    if [ $? -ne 0 ]; then
        echo "generate_sites_manifest.sh 执行失败，提交已取消。"
        exit 1
    fi

    # 自动把生成的文件加入本次 commit
    if [ -f assets/sites_manifest.json ]; then
        git add assets/sites_manifest.json
        echo "assets/sites_manifest.json 已加入本次提交。"
    else
        echo "警告: assets/sites_manifest.json 没有生成！"
    fi
fi

exit 0
